Update/nelson ansible
SemkoDev/nelson.cli pull request #42
Opened 2018-01-06 21:18 UTC by nuriel77

Some updates to the iri-nelson ansible docker playbook.
Including up-to-date nelson configuration, iri configuration and docs update.

2018-01-09 01:12 UTC, romansemko commented on contrib/ansible-playbook/roles/nelson/templates/config.ini.j2
> +neighbors[] = mainnet.deviota.com/14600
Hmm, why did this change? The Nelson ports are still 16600 on mainnets...

2018-01-09 01:12 UTC, romansemko requested changes
The mainnet ports seem to be off...

2018-01-09 20:19 UTC, nuriel77 commented on contrib/ansible-playbook/roles/nelson/templates/config.ini.j2
> +neighbors[] = mainnet.deviota.com/14600
I took the example from the config file here https://github.com/SemkoDev/nelson.cli/blob/master/config.ini.example

Will change back to 14600

2018-01-10 06:34 UTC, romansemko approved these changes

2018-01-10 06:34 UTC, merged